# Generated by Django 6.0 on 2026-02-11 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('license_plate', models.CharField(max_length=20)),
                ('location', models.CharField(choices=[('koblenz', 'Koblenz'), ('frankfurt', 'Frankfurt'), ('berlin', 'Berlin')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_service_date', models.DateField(blank=True, help_text='Date when the car was last serviced', null=True)),
                ('remarks', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(db_index=True, editable=False, max_length=12, unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('destination', models.CharField(blank=True, max_length=200)),
                ('project_no', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(default='CONFIRMED', max_length=50)),
                ('booked_by', models.CharField(help_text='Name of the user who booked the car from Microsoft login', max_length=150)),
                ('client_name', models.CharField(blank=True, help_text='Name of the passenger for whom the car is booked', max_length=150, null=True)),
                ('current_time', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='home.car')),
            ],
        ),
    ]
