# Generated by Django 6.0 on 2025-12-12 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='vehicle',
            new_name='Car',
        ),
    ]
