# Generated by Django 6.0 on 2025-12-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_car_is_active_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='project_no',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
