# Generated by Django 6.0 on 2025-12-15 11:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_booking_project_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='current_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
