# Generated by Django 6.0 on 2025-12-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_booking_current_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='remarks',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
