# Generated by Django 6.0 on 2025-12-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_car_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_by',
            field=models.CharField(default='', help_text='Name of the user who booked the car from Microsoft login', max_length=150),
            preserve_default=False,
        ),
    ]
