# Generated by Django 6.0 on 2025-12-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_booking_booked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client_name',
            field=models.CharField(blank=True, help_text='Name of the passenger for whom the car is booked', max_length=150, null=True),
        ),
    ]
