# Generated by Django 6.0 on 2026-01-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_booking_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='location',
            field=models.CharField(choices=[('koblenz', 'Koblenz'), ('frankfurt', 'Frankfurt'), ('berlin', 'Berlin')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
